version: "2.1"
services:
 elasticsearch:
  image: 'elasticsearch:7.6.1'
  #deployment_strategy: every_node
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9200"]
    interval: 10s
    timeout: 10s
    retries: 60
  ports:
  - '9200:9200'
  - '9300:9300'
  ulimits:
    memlock:
      soft: -1
      hard: -1
  environment:
  - bootstrap.memory_lock=false
  - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  - cluster.initial_master_nodes=elasticsearch
  - node.master=true
  - discovery.zen.minimum_master_nodes=1
  - node.name=elasticsearch

 app:
   image: mysciencework/polarisos:1.0.1
   healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:8080"]
     interval: 10s
     timeout: 10s
     retries: 60
   depends_on:
    elasticsearch:
     condition: service_healthy
   volumes:
   - ./app:/tmp
   ports:
   - "8080:5556"
   entrypoint: "bash -c 'chmod +x /tmp/start-app.sh; /tmp/start-app.sh'"

 bootstrap:
   image: mysciencework/polarisos-bootstrap:0.2
   healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:8080"]
     interval: 10s
     timeout: 10s
     retries: 60
   depends_on:
    elasticsearch:
     condition: service_healthy
    app:
     condition: service_healthy
